
     - name: install python gcc 
       ansible.builtin.dnf: 
          name: "{{ item }}"
          state: present 
       loop: 
         - python3 
         - gcc
         - python3-devel 
         
     - name: Create roboshop user 
       ansible.builtin.include_role:
        name: common 
        tasks_from: roboshop_user.yaml
     
     - name: delete existing and create new app dir 
       ansible.builtin.include_role: 
        name: common 
        tasks_from: app_dir.yaml

     - name: delete and get the {{ component }} code 
       ansible.builtin.include_role: 
        name: common 
        tasks_from: app_code.yaml

     - name: Install specified python requirements
       ansible.builtin.pip:
          requirements: requirements.txt
          executable: pip3
       args:   
          chdir: /app

    
     - name: copy {{ component }} service to /etc/systemd/system/{{ component }}.service
       ansible.builtin.template:
        src: payment.service.j2
        dest: /etc/systemd/system/payment.service
       notify:
        - payment daemon reload
        - start payment service