
  - name: Enable and install nodejs 
    ansible.builtin.include_role: 
      name: common 
      tasks_from: nodejs_install.yaml
       
  - name: Create roboshop user 
    ansible.builtin.include_role:
       name: common 
       tasks_from: roboshop_user.yaml

  - name: delete and get the {{ component }} code 
    ansible.builtin.include_role: 
      name: common 
      tasks_from: app_code.yaml

  - name: Install npm
    community.general.npm:
      path: /app
      state: latest

  - name: configure mongosh and upload DB
    ansible.builtin.include_role:
      name: common 
      tasks_from: mongo_config.yaml

  - name: copy {{ component }} service to /etc/systemd/system/{{ component }}.service
    ansible.builtin.template:
      src: "{{ component }}.service.j2"
      dest: /etc/systemd/system/{{ component }}.service
    notify:
      - daemon reload
      - start "{{ component }}" service

