  - name: payment daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: payment

  - name: start payment service
    ansible.builtin.service:
      name: payment
      state: restarted
      enabled: true