  - name: cart daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
      name: cart

  - name: start cart service
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: true